# Homework I - ME 364 (Spring 2022)

**Question I :** Define a list with 5 elements, where at least one of the elements is a tuple itself. Then write a for-loop to print each element on a new line.

In [ ]:
# Your code goes here
lizlist=['spicy', "crunchy","salmon", "bites",(2,0,2,2)]
for var in lizlist:
    print(var)
    print('                                   ')


spicy
                                   
crunchy
                                   
salmon
                                   
bites
                                   
(2, 0, 2, 2)
                                   


**Question II :** Define a list with numbers from 1 to 6. Then add the numbers 7, 8, 9, 10, and 11 to the list

(a) using just one command

(b) using a loop and adding the numbers one by one

In [ ]:
# Your code goes here
numlista=[1,2,3,4,5,6]
numlista.extend([7,8,9,10,11]) #a
print(numlista)

numlistb=[1,2,3,4,5,6]
add=[7,8,9,10,11]
for value in add:                   #b
        numlistb.append(value) 

print(numlistb)
    

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


**Quesion III :** Write a code that adds a new $key-value$ (of your choice) to
```python
SampleDictionary = {'ME 364' : '9am', 'Pyhon for Data Analysis' : '6:10pm', 'Reinforcement Learning' : '10am'}
```
Removes the $key-value$ ``` 'Reinforcement Learning' : '10am' ```, and then creates a _list_ of the $values$.


In [ ]:
# Your code goes here
SampleDictionary = {'ME 364' : '9am', 'Pyhon for Data Analysis' : '6:10pm', 'Reinforcement Learning' : '10am'}
print(SampleDictionary)
SampleDictionary['Cooper Union']=['sometimes problematic', 'i wish it was free']
print(SampleDictionary)
del SampleDictionary['Reinforcement Learning']
print(SampleDictionary)

print('\n')
list(SampleDictionary.values())


{'ME 364': '9am', 'Pyhon for Data Analysis': '6:10pm', 'Reinforcement Learning': '10am'}
{'ME 364': '9am', 'Pyhon for Data Analysis': '6:10pm', 'Reinforcement Learning': '10am', 'Cooper Union': ['sometimes problematic', 'i wish it was free']}
{'ME 364': '9am', 'Pyhon for Data Analysis': '6:10pm', 'Cooper Union': ['sometimes problematic', 'i wish it was free']}




['9am', '6:10pm', ['sometimes problematic', 'i wish it was free']]

**Question IV :** Convert the following string
```python
Str = 'This string is written for homework I'
```
into a list and then slice it such that the outcome is
```python
['T', 'i', ' ', 't', 'i', 'g', 'i', ' ', 'r', 't', 'e', ' ', 'o', ' ', 'o', 'e', 'o', 'k', 'I']
```

In [ ]:
# Your code goes here
Str = 'This string is written for homework I'

def Convert(string):
    list2slice=[]
    list2slice[:0]=str
    return list2slice

str = 'This string is written for homework I'
print(Convert(str))


['T', 'h', 'i', 's', ' ', 's', 't', 'r', 'i', 'n', 'g', ' ', 'i', 's', ' ', 'w', 'r', 'i', 't', 't', 'e', 'n', ' ', 'f', 'o', 'r', ' ', 'h', 'o', 'm', 'e', 'w', 'o', 'r', 'k', ' ', 'I']


**Question V :** Write a function that adds the numbers from 1 to N, where N is the input to the function and the sum from 1 to N is the output.  Test it with N=100.

In [ ]:
# Your code goes here
def addup(N):
    return sum(range(N+1))

print('sum:',addup(100), 'input:', 100)


sum: 5050 input: 100


**Question VI :** The Chudnovsky series for approximating $\pi$ was used to obtain the world record for digits of $\pi$, 2.7 trillion digits! The
following series is a modified version of that series:

$$
12 \sum_{k=1}^N\frac{(-1)^k(6k)(1359+5451k)}{(3k)(k^3)(6^{3k+3/2})}
$$

Write a code that computs this series for N=10. 

<font color='blue'>Note:</font> The series no longer approximate $\frac{1}{\pi}$ since it has been modified.




In [ ]:
# Your code goes here
import numpy as np

list=[]
def chudnovsky(n):
    k=1
    while k<n:
        chud=(((-1)**k)*(6*k)*(1359+(5451*k)))/(((3*k)*(k**3))*(6**((3*k)+(3/2))))
        list.append(chud)
        k += 1
    return chud
chudnovsky(11)
print("All elements returned from series",list)
print("Sum of elements in series",sum(list))
Ans=12*sum(list)
print("Answer (12*sum of elements):",Ans)

All elements returned from series [-4.2903871266341165, 0.004470247029122214, -8.858204578516563e-06, 2.26257481523141e-08, -6.625259967339388e-11, 2.1131739840288563e-13, -7.146702745256284e-16, 2.522301883695887e-18, -9.195544392542531e-21, 3.439034293557828e-23]
Sum of elements in series -4.285925715249867
Answer (12*sum of elements): -51.431108582998405


**Question VII:** Consider matrix
$A=\begin{bmatrix} 10 & 15 & 8 & 23 & 13\\ 19 & 22 & 45 & 3 & 34\\ 52 & 55 & 40 & 16 & 12\end{bmatrix}$

(a) Find a matrix that its elements are the squre roots of this matrix's elements.

(b) Calculate $(A^{T}A)^{-1}$

(c) Find the sum of all the elements across the columns and standard deviation for each column.

(d) Sort the elements down the rows.

(e) Make a slice that has the elements on rows 2 and 3 and columns 2 to 4

(f) Reshape the matrix into the following array:
$\begin{bmatrix} 10 & 15 & 8 & 23 & 13 & 19 & 22 & 45 & 3 & 34 & 52 & 55 & 40 & 16 & 12\end{bmatrix}$



In [ ]:
# Your code goes here
import numpy as np

A=np.matrix([[10,15,8,23,13],[19,22,45,3,34],[52,55,40,16,12]])
#print(A)
B=np.sqrt(A)
print('Part A:\n ', B)
print('\n')
Atr=np.transpose(A)
A2=Atr.dot(A)
#print(A2)
#print('\n')
A3=np.linalg.inv(A2)
print('Part B:\n',A3)
print('\n')

print('Sum across columns for Part C:\n', np.sum(A,axis=1))
print('SD for each column for Part C:\n',np.std(A,axis=0))
print('\n')

print('Part D:')
a = np.array([[10,15,8,23,13], [19,22,45,3,34], [52,55,40,16,12]])
print('Original Array:\n',a)
print('')
a.sort(axis=0)              # sorting the values across the columns
print('Array with values sorted down the rows:\n',a)

print('\n')

print('Part E:', A[1:3,1:4])

print('\n')

A4=A.reshape((1,15 ))
print('Part F:',A4)



Part A:
  [[3.16227766 3.87298335 2.82842712 4.79583152 3.60555128]
 [4.35889894 4.69041576 6.70820393 1.73205081 5.83095189]
 [7.21110255 7.41619849 6.32455532 4.         3.46410162]]


Part B:
 [[-3.63554147e+12  5.46172830e+12 -2.48306347e+12 -2.23757826e+12
   1.98140753e+12]
 [ 7.33302725e+12 -8.28384971e+12  1.16884197e+12  2.07194931e+12
  -4.67545909e+11]
 [-5.11237264e+12  3.84080113e+12  1.90316852e+12  2.83718640e+11
  -2.17224365e+12]
 [-3.90937468e+12  3.43177975e+12  7.60156187e+11 -2.25057783e+11
  -1.02214385e+12]
 [ 4.39804651e+12 -3.07822160e+12 -1.95468734e+12 -4.45913626e+11
   2.16049008e+12]]


Sum across columns for Part C:
 [[ 69]
 [123]
 [175]]
SD for each column for Part C:
 [[18.05547009 17.44196727 16.39105447  8.28653526 10.14341604]]


Part D:
Original Array:
 [[10 15  8 23 13]
 [19 22 45  3 34]
 [52 55 40 16 12]]

Array with values sorted down the rows:
 [[10 15  8  3 12]
 [19 22 40 16 13]
 [52 55 45 23 34]]


Part E: [[22 45  3]
 [55 40 16]]


Part F: [[